language: node_js
node_js:
  - "6"
  - "8"
  - "9"
  - "10"
  - "11"

os:
  - windows
  - linux
  - osx

before_script:
  - npm update --dev
  - cd ./examples/aml-check && npm update && cd ../../
  - cd ./examples/profile && npm update && cd ../../

script:
  - if: NOT os = windows
    npm run lint
  - npm test
