language: node_js

node_js:
  - "6"
  - "8"
  - "9"
  - "10"
  - "11"
  - "node"

os:
  - linux
  - osx

cache: npm

git:
  depth: 1

before_install: npm install -g npm@latest

install: npm ci

script:
  - npm audit
  - npm run lint
  - npm test
  - npm update
  - npm run lint
  - npm test

jobs:
  include:
    - stage: Profile Example Lint
      node_js: "10"
      install: cd ./examples/aml-check && npm update
      script:
        - npm run lint
    - stage: AML Check Example Lint
      node_js: "10"
      install: cd ./examples/aml-check && npm update
      script:
        - npm run lint
