language: node_js

cache: npm

git:
  depth: 1

os:
  - linux
  - osx

jobs:
  include:
    - stage: Test SDK
      install: npm ci
      script:
        - npm run lint
        - npm test
    - stage: Check latest dependencies
      install: npm update
      script:
        - npm run lint
        - npm test
    - stage: Profile Example
      install: cd ./examples/aml-check && npm update
      script:
        - npm run lint
    - stage: AML Check Example
      install: cd ./examples/aml-check && npm update
      script:
        - npm run lint
