language: node_js

cache: npm

git:
  depth: 1

tasks:
  - &test
    stage: Test
    node_js: "10"
    before_install: npm install -g npm@latest
    install: npm ci
    script:
      - npm audit
      - npm test
  - &test-latest
    stage: Compatibility
    node_js: "node"
    os: linux
    install: npm update
    script:
      - npm test
  - &test-latest-osx
    <<: *test-latest
    os: osx
  - &lint-examples
    stage: Lint Examples
    node_js: "10"
    script:
      - npm run lint

jobs:
  include:
    - <<: *test
    - <<: *test-latest
    - <<: *test-latest
      node_js: "6"
    - <<: *test-latest
      node_js: "8"
    - <<: *test-latest
      node_js: "9"
    - <<: *test-latest
      node_js: "10"
    - <<: *test-latest
      node_js: "11"
      <<: *test-latest-osx
    - <<: *test-latest-osx
      node_js: "10"
    - <<: *lint-examples
      install:
        - cd ./examples/aml-check
        - npm update
    - <<: *lint-examples
      install:
        - cd ./examples/profile
        - npm update
